name: snowflake-prod-migration

on:
  push:
    branches:
      - sf-prod
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # List contents of the repository
      - name: List repository contents
        run: ls -R $GITHUB_WORKSPACE

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_PROD_DATABASE: ${{ secrets.SF_PROD_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          pip install schemachange
          schemachange deploy -f $GITHUB_WORKSPACE/deploy -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_PROD_DATABASE -c $SF_PROD_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
